<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Contattaci in un Tocco!</h2>
                <hr class="primary">
                <p>Sei pronto a vivere un'esperienza indimenticabile ? Non esitare a contattarci!</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-phone fa-3x wow bounceIn text-primary"></i>
                <p><a href="tel:+393391774387">339 177 43 87</a></p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn text-primary" data-wow-delay=".1s"></i>
                <p><a href="mailto:gdeluca1969@gmail.com">gdeluca1969@gmail.com</a></p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-facebook-official fa-3x wow bounceIn text-primary" data-wow-delay=".1s"></i>
                <p><a href="http://www.facebook.com/privatetransferamalficoast" target="_blank">Amalfitourscarservice</a></p>
            </div>
        </div>

    </div>
</section>