<?php 
/*
$id = 15; $p = get_page($id); echo apply_filters('the_content', $p->post_content); 
*/
?>

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Tutto ciò di cui avete bisogno!</h2>
                <hr class="light">
                <p class="text-faded">Lascia a casa la tua auto al resto ci pensa Giosy! Professionalità e competenza... Per maggiori informazioni contattatemi al numero</p>
                <a href="tel:+393391774387" class="btn btn-default btn-xl">339 177 43 87</a>
            </div>
        </div>
    </div>
</section>

<section class="no-padding">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-6 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="<?php echo get_template_directory_uri(); ?>/img/taxi_1.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">                               
                                Servizi
                            </div>
                            <div class="project-name">
                                Noleggio Con Conducente
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-6 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="<?php echo get_template_directory_uri(); ?>/img/taxi_2.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Servizi
                            </div>
                            <div class="project-name">
                                Servizi per Hotels
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">I nostri servizi</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-car wow bounceIn text-primary"></i>
                    <h3>NCC</h3>
                    <p class="text-muted">Servizi di noleggio auto con conducente...</p>
                    <br />
                    <a href="#" class="btn btn-primary btn-xl wow tada">Scopri di più!</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-map wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>Escursioni</h3>
                    <p class="text-muted">Disponibile ad un'ampia varietà di escursioni personalizzate...</p>
                    <br />
                    <a href="#" class="btn btn-primary btn-xl wow tada">Scopri di più!</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-bed wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Hotels</h3>
                    <p class="text-muted">City tour; Shopping tour...</p>
                    <br />
                    <a href="#" class="btn btn-primary btn-xl wow tada">Scopri di più!</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-plane wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>Servizi</h3>
                    <p class="text-muted">Trasferimenti per Aeroporto, Stazione treni e Imbarchi...</p>
                    <br />
                    <a href="#" class="btn btn-primary btn-xl wow tada">Scopri di più!</a>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="no-padding" id="excursions">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="<?php echo get_template_directory_uri(); ?>/img/portfolio/1.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">                               
                                Excursions
                            </div>
                            <div class="project-name">
                                Amalfi
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="<?php echo get_template_directory_uri(); ?>/img/portfolio/2.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Excursions
                            </div>
                            <div class="project-name">
                                Ravello
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="<?php echo get_template_directory_uri(); ?>/img/portfolio/3.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Excursions
                            </div>
                            <div class="project-name">
                                Positano
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="<?php echo get_template_directory_uri(); ?>/img/portfolio/4.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Excursions
                            </div>
                            <div class="project-name">
                                Sorrento
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="<?php echo get_template_directory_uri(); ?>/img/portfolio/5.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Excursions
                            </div>
                            <div class="project-name">
                                Napoli
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <img src="<?php echo get_template_directory_uri(); ?>/img/portfolio/6.jpg" class="img-responsive" alt="">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Excursions
                            </div>
                            <div class="project-name">
                                Paestum
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Scarica il depliant con i dettagli e le tariffe</h2>
            <a href="#" class="btn btn-default btn-xl wow tada">Scarica!</a>
        </div>
    </div>
</aside>