--
-- Struttura della tabella `p_verb`
--

CREATE TABLE IF NOT EXISTS `p_verb` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NUM_VERB` int(11) NOT NULL,
  `DATA_VERB` date NOT NULL,
  `ORA_VERB` varchar(5) NOT NULL,
  
  `ENTE_VERB` varchar(5) NOT NULL,
  `NOME_ENTE_VERB` varchar(256) NOT NULL,
  `CCP_ENTE_VERB` int(11) NOT NULL,
  `IBAN` varchar(100) NOT NULL,
  
  `TIPO_VEI_ID_VERB` varchar(3) NOT NULL,
  `TIPO_VEI_DESCR_VERB` varchar(50) NOT NULL,
  `TARGA_VERB` varchar(10) NOT NULL,
  `MODELLO_VERB` varchar(25) NOT NULL,
  
  `ID_VIA_VERB` int(11) NOT NULL,
  `VIA_DESCR_VERB` varchar(100) NOT NULL,
  `CIVICO_VERB` varchar(10) NOT NULL,
  `DESCR_VIA_VERB` varchar(70) NOT NULL,
  
  `ART1_VERB_ID` int(11) NOT NULL,
  `ART1_COD1_VERB` varchar(5) NOT NULL,
  `ART1_DESCR_VERB` varchar(70) NOT NULL,
  `ART1_PUNTI_VERB` int(11) NOT NULL,
  `ART1_IMPORTO_VERB` int(11) NOT NULL,
  `ART1_ID_SANZ_ACC_VERB` varchar(10) NOT NULL,
  `ART1_DESC_SANZ_ACC_VERB` varchar(256) NOT NULL,
  
  `ART2_VERB_ID` int(11) NOT NULL,
  `ART2_COD1_VERB` varchar(5) NOT NULL,
  `ART2_DESCR_VERB` varchar(70) NOT NULL,
  `ART2_PUNTI_VERB` int(11) NOT NULL,
  `ART2_IMPORTO_VERB` int(11) NOT NULL,
  `ART2_ID_SANZ_ACC_VERB` varchar(10) NOT NULL,
  `ART2_DESC_SANZ_ACC_VERB` varchar(256) NOT NULL,
  
  `NOTE_VERB` varchar(256) NOT NULL,
  `DESC_MANC_CONT_VERB` varchar(256) NOT NULL,
  
  `COD_OBLG_VERB` int(11) NOT NULL,
  `COD_TRSG_VERB` int(11) NOT NULL,
  
  `IMG_VERB` longblob NOT NULL,
  `FILE_PATH_IMG_VERB` varchar(200) NOT NULL,
  `LATI_VERB` varchar(50) NOT NULL,
  `LONG_VERB` varchar(50) NOT NULL,
  
  `ID_AGENTE1_VERB` int(11) NOT NULL,
  `ID_AGENTE2_VERB` int(50) NOT NULL,
  `NOME_AGENT1_VERB` varchar(50) NOT NULL,
  `NOME_AGENT2_VERB` varchar(50) NOT NULL,

  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=31 ;
