-- MySQL Script generated by MySQL Workbench
-- 06/09/17 16:01:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easycomandeBE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easycomandeBE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easycomandeBE` DEFAULT CHARACTER SET utf8 ;
USE `easycomandeBE` ;

-- -----------------------------------------------------
-- Table `easycomandeBE`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomandeBE`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomandeBE`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomandeBE`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomandeBE`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomandeBE`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomandeBE`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomandeBE`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomandeBE`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomandeBE`.`notes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easycomandeBE`.`specials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easycomandeBE`.`specials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
