ALTER TABLE p_verb
ADD `IMG1_VERB` longblob NOT NULL AFTER `FILE_PATH_IMG_VERB`;
ALTER TABLE p_verb
ADD `FILE_PATH_IMG1_VERB` varchar(200) NOT NULL AFTER `IMG1_VERB`;
ALTER TABLE p_verb
ADD `IMG2_VERB` longblob NOT NULL AFTER `FILE_PATH_IMG1_VERB`;
ALTER TABLE p_verb
ADD `FILE_PATH_IMG2_VERB` varchar(200) NOT NULL AFTER `IMG2_VERB`;